# Generated by Django 3.2.15 on 2022-11-15 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='phone',
            fields=[
                ('create_at', models.DateTimeField(auto_created=True)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('model', models.CharField(max_length=256)),
                ('price', models.IntegerField(blank=True)),
                ('count', models.IntegerField()),
            ],
        ),
    ]
