# Generated by Django 3.2.15 on 2022-11-28 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Samsung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(blank=True, max_length=256)),
            ],
            options={
                'verbose_name': 'Samsung',
                'verbose_name_plural': 'Samsung',
            },
        ),
        migrations.CreateModel(
            name='Samsung123',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(blank=True, max_length=256)),
            ],
            options={
                'verbose_name': 'Samsung',
                'verbose_name_plural': 'Samsung',
            },
        ),
    ]
