# Generated by Django 3.2.15 on 2022-11-28 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(blank=True, max_length=256, verbose_name='Phone')),
            ],
            options={
                'verbose_name': 'IPhone',
                'verbose_name_plural': 'IPhone',
            },
        ),
        migrations.CreateModel(
            name='MI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(blank=True, max_length=256, verbose_name='Phone')),
            ],
            options={
                'verbose_name': 'MI',
                'verbose_name_plural': 'MI',
            },
        ),
        migrations.CreateModel(
            name='Phones',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('model', models.CharField(max_length=256)),
                ('price', models.IntegerField(verbose_name='Price')),
                ('description', models.TextField(verbose_name='Descriptions')),
            ],
            options={
                'verbose_name': 'Phone',
                'verbose_name_plural': 'Phones',
            },
        ),
        migrations.DeleteModel(
            name='Samsung123',
        ),
        migrations.AlterField(
            model_name='samsung',
            name='model_name',
            field=models.CharField(blank=True, max_length=256, verbose_name='Phone'),
        ),
    ]
