# Generated by Django 3.2.15 on 2022-11-28 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20221128_2001'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MI',
            new_name='Company',
        ),
        migrations.DeleteModel(
            name='IPhone',
        ),
        migrations.DeleteModel(
            name='Samsung',
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Company', 'verbose_name_plural': 'Companys'},
        ),
        migrations.AddField(
            model_name='phones',
            name='company_name',
            field=models.ForeignKey(blank=True, max_length=256, null=True, on_delete=django.db.models.deletion.PROTECT, to='mainapp.company'),
        ),
    ]
