# Generated by Django 3.2.15 on 2022-12-04 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20221128_2005'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Производитель', 'verbose_name_plural': 'Производители'},
        ),
        migrations.AlterModelOptions(
            name='phones',
            options={'verbose_name': 'Телефон', 'verbose_name_plural': 'Телефоны'},
        ),
        migrations.AddField(
            model_name='phones',
            name='img',
            field=models.ImageField(null=True, upload_to='', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='phones',
            name='company_name',
            field=models.ForeignKey(blank=True, max_length=256, null=True, on_delete=django.db.models.deletion.PROTECT, to='mainapp.company', verbose_name='Производитель'),
        ),
        migrations.AlterField(
            model_name='phones',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='phones',
            name='model',
            field=models.CharField(max_length=256, verbose_name='Модель'),
        ),
        migrations.AlterField(
            model_name='phones',
            name='price',
            field=models.IntegerField(verbose_name='Цена'),
        ),
    ]
