# Generated by Django 3.2.15 on 2022-12-11 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_auto_20221204_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='phones',
            name='slug',
            field=models.SlugField(max_length=255, null=True, unique=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='phones',
            name='img',
            field=models.ImageField(null=True, upload_to='static/img/', verbose_name='Изображение'),
        ),
    ]
